apps/users/urls.py
from django.urls import path
# from .views import sign_up, user_login, complete_profile, view_profile, logout, edit_user_info, save_user_info,
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'users'

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.user_login, name='login'),
    path('complete-profile/', views.complete_profile, name='complete_profile'),
    path('profile/', login_required(views.view_profile, login_url='/users/login/'), name='profile'),
    path('logout/', views.logout_user, name='logout_user'),
    path('edit_demographic_info_form/', views.edit_demographic_info_form, name='edit_demographic_info_form'),
    path('edit_demographic_info/', views.edit_demographic_info, name='edit_demographic_info'),
    path('edit_medical_hist_form/', views.edit_medical_hist_form, name='edit_medical_hist_form'),
    path('edit_med_hist/', views.edit_med_hist, name='edit_med_hist'),
    path('edit_lifestyle_info_form/', views.edit_lifestyle_info_form, name='edit_lifestyle_info_form'),
    path('edit_lifestyle_info/', views.edit_lifestyle_info, name='edit_lifestyle_info'),
    path('edit_biometric_data/', views.edit_biometric_data, name='edit_biometric_data'),
    path('edit_biometric_data_form/', views.edit_biometric_data_form, name='edit_biometric_data_form'),
    path('edit_env_factors/', views.edit_env_factors, name='edit_env_factors'),
    path('edit_env_factors_form/', views.edit_env_factors_form, name='edit_env_factors_form'),    
]

sshms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.main.urls', namespace='main')),
    path("admin/", admin.site.urls),
    path('prediction/', include('apps.prediction.urls', namespace='prediction')),
    path('users/', include('apps.users.urls', namespace='users'))
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField()
    sex = models.CharField(max_length=10)
    ethnicity_race = models.CharField(max_length=100, blank=True)
    socioeconomic_status = models.CharField(max_length=100, blank=True)
    family_history_chronic_diseases = models.TextField(blank=True)
    diagnosed_chronic_conditions = models.TextField(blank=True)
    medications = models.TextField(blank=True)
    surgeries = models.TextField(blank=True)
    typical_daily_diet = models.CharField(max_length=50, blank=True)
    physical_activity_frequency = models.CharField(max_length=50, blank=True)
    smoking_habits = models.CharField(max_length=100, blank=True)
    alcohol_consumption = models.CharField(max_length=100, blank=True)
    recreational_drug_use = models.CharField(max_length=100, blank=True)
    stress_management_methods = models.CharField(max_length=100, blank=True)
    height = models.DecimalField(max_digits=5, decimal_places=2)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    blood_pressure = models.CharField(max_length=20, blank=True)
    cholesterol_levels = models.CharField(max_length=20, blank=True)
    blood_glucose_levels = models.CharField(max_length=20, blank=True)
    air_pollution_exposure = models.BooleanField(default=False)
    occupational_hazards = models.BooleanField(default=False)
    clean_drinking_water_access = models.BooleanField(default=True)
    genetic_conditions = models.TextField(blank=True)
    genetic_testing_results = models.TextField(blank=True)
    medical_compliance = models.CharField(max_length=20, blank=True)
    health_literacy = models.CharField(max_length=20, default='Moderate')
    mental_health_diagnosis = models.TextField(blank=True)
    social_support_network = models.TextField(blank=True)
    occupation = models.CharField(max_length=100, blank=True)
    work_stress = models.TextField(blank=True)
    last_checkup = models.DateField(null=True, blank=True)  # Changed default value to null
    cancer_screening = models.TextField(blank=True)
    residential_area = models.CharField(max_length=100, blank=True)
    access_to_healthcare = models.BooleanField(default=True)
    additional_comments = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.user.username

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150, label="Username")
    password = forms.CharField(widget=forms.PasswordInput(), label="Password")
    


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['age', 'sex', 'ethnicity_race', 'socioeconomic_status', 'family_history_chronic_diseases', 'diagnosed_chronic_conditions', 'medications', 'surgeries', 'typical_daily_diet', 'physical_activity_frequency', 'smoking_habits', 'alcohol_consumption', 'recreational_drug_use', 'stress_management_methods', 'height', 'weight', 'blood_pressure', 'cholesterol_levels', 'blood_glucose_levels', 'air_pollution_exposure', 'occupational_hazards', 'clean_drinking_water_access', 'genetic_conditions', 'genetic_testing_results', 'medical_compliance', 'health_literacy', 'mental_health_diagnosis', 'social_support_network', 'occupation', 'work_stress', 'last_checkup', 'cancer_screening', 'residential_area', 'access_to_healthcare', 'additional_comments']


class DemographicInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['age', 'sex', 'ethnicity_race', 'socioeconomic_status']   
        
class MedicalHistForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['family_history_chronic_diseases', 'diagnosed_chronic_conditions', 'medications', 'surgeries']
        
class LifestyleInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['typical_daily_diet', 'physical_activity_frequency', 'smoking_habits', 'alcohol_consumption', 'recreational_drug_use', 'stress_management_methods']
        
class BiometricDataForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['height', 'weight', 'blood_pressure', 'cholesterol_levels', 'blood_glucose_levels']
        
class EnvironmentalFactorsForm(forms.Form):
    air_pollution_exposure = forms.BooleanField(required=False)
    occupational_hazards = forms.BooleanField(required=False)
    clean_drinking_water_access = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['air_pollution_exposure'].widget = forms.Select(choices=[(True, 'Yes'), (False, 'No')])
        self.fields['occupational_hazards'].widget = forms.Select(choices=[(True, 'Yes'), (False, 'No')])
        self.fields['clean_drinking_water_access'].widget = forms.Select(choices=[(True, 'Yes'), (False, 'No')])

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.models import User
from .forms import EnvironmentalFactorsForm, BiometricDataForm, LifestyleInfoForm, SignUpForm, UserLoginForm, ProfileForm, DemographicInfoForm, MedicalHistForm
from .models import UserProfile
from apps.prediction.models import Prediction

def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('users:complete_profile')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                
                next_url = request.GET.get('next')
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect('main:home')
            else:
                messages.error(request, 'Invalid username or password')
    else:
        form = UserLoginForm()
        
    context = {
        'form': form,
        'next': request.GET.get('next', '')
    }
    
    return render(request, 'users/login.html', context)

@login_required
def complete_profile(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)
        
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save()
            return redirect('users:profile')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'users/complete_profile.html', {'form': form})

@login_required
def view_profile(request):
    try:
        # profile = UserProfile(user=request.user)
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = None
        
    user_predictions = request.user.predictions.all()
    context = {
        'profile': profile,
        'predictions': user_predictions,
    }
    return render(request, 'users/profile.html', context)

def logout_user(request):
    logout(request)
    request.session.flush()
    # return redirect('users:login')
    return render(request, 'users/logout.html')


@login_required
def edit_demographic_info_form(request):
    profile = request.user.userprofile
    form = DemographicInfoForm(instance=profile)
    return render(request, 'users/demographic_info_form.html', {'form': form})

@login_required
def edit_demographic_info(request):
    profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        form = DemographicInfoForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save()
            return JsonResponse({
                'success': True,
                'age': profile.age,
                'sex': profile.sex,
                'ethnicity_race': profile.ethnicity_race,
                'socioeconomic_status': profile.socioeconomic_status
            })
        else:
            return JsonResponse({'success': False, 'message': 'Form is invalid'})
    else:
        form = DemographicInfoForm(instance=profile)

    return render(request, 'users/demographic_info_form.html', {'form': form})

@login_required
def edit_medical_hist_form(request):
    profile = request.user.userprofile
    form = MedicalHistForm(instance=profile)
    return render(request, 'users/edit_med_hist_form.html', {'form': form})

@login_required
def edit_med_hist(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    
    if request.method == 'POST':
        form = MedicalHistForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save()
            return JsonResponse({
                'success': True,
                'family_history_chronic_diseases': profile.family_history_chronic_diseases,
                'diagnosed_chronic_conditions': profile.diagnosed_chronic_conditions,
                'medications': profile.medications,
                'surgeries': profile.surgeries
            })
        else:
            return JsonResponse({'success': False, 'message': 'Form is invalid'})
    else:
        form = MedicalHistForm(instance=profile)
        
    return render(request, 'users/edit_med_hist_form.html', {'form': form})


@login_required
def edit_lifestyle_info_form(request):
    profile = request.user.userprofile
    form = LifestyleInfoForm(instance=profile)
    return render(request, 'users/edit_lifestyle_info_form.html', {'form': form})

@login_required
def edit_lifestyle_info(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    
    if request.method == 'POST':
        form = LifestyleInfoForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save()
            return JsonResponse({
                'success': True,
                'typical_dail_diet': profile.typical_daily_diet,
                'physical_activity_frequency': profile.physical_activity_frequency,
                'smoking_habits': profile.smoking_habits,
                'alcohol_consumption': profile.alcohol_consumption,
                'recreational_drug_use': profile.recreational_drug_use,
                'stress_management_methods': profile.stress_management_methods
            })
        else:
            return JsonResponse({'success': False, 'message': 'Form is invalid'})
    else:
        form = LifestyleInfoForm(instance=profile)
        
    return render(request, 'users/edit_lifestyle_info_form.html', {'form': form})

@login_required
def edit_biometric_data_form(request):
    profile = request.user.userprofile
    form = BiometricDataForm(instance=profile)
    return render(request, 'users/edit_biometric_data_form.html', {'form': form})

@login_required
def edit_biometric_data(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    
    if request.method == 'POST':
        form = BiometricDataForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save()
            return JsonResponse({
                'success': True,
                'height': profile.height,
                'weight': profile.weight,
                'blood_pressure': profile.blood_pressure,
                'cholesterol_levels': profile.cholesterol_levels,
                'blood_glucose_levels': profile.blood_glucose_levels
            })
        else:
            return JsonResponse({'success': False, 'message': 'Form is invalid'})
    else:
        form = BiometricDataForm(instance=profile)
    
    return render(request, 'users/edit_biometric_data_form.html', {'form': form})\
 
@login_required
def edit_env_factors_form(request):
    return render(request, 'users/edit_env_factors_form.html', {'form': EnvironmentalFactorsForm()})

@login_required
def edit_env_factors(request):
    profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        form = EnvironmentalFactorsForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save()
            return JsonResponse({
                'success': True,
                'air_pollution_exposure': profile.air_pollution_exposure,
                'occupational_hazards': profile.occupational_hazards,
                'clean_drinking_water_access': profile.clean_drinking_water_access
            })
        else:
            return JsonResponse({'success': False, 'message': 'Form is invalid!'})
    else:
        form = EnvironmentalFactorsForm(instance=profile)
        return render(request, 'users/edit_env_factors_form.html', {'form': form})

apps/users/templates/users/demographic_info_form.html
<!-- Your HTML form -->
<form id="demographic-info-form" method="post" action="{% url 'users:edit_demographic_info' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="id_age" class="block text-gray-700 text-sm font-bold mb-2">Age</label>
        {{ form.age }}
    </div>
    <div class="mb-4">
        <label for="id_gender" class="block text-gray-700 text-sm font-bold mb-2">Gender</label>
        {{ form.sex }}
    </div>
    <div class="mb-4">
        <label for="id_ethnicity_race" class="block text-gray-700 text-sm font-bold mb-2">Ethnicity / Race</label>
        {{ form.ethnicity_race }}
    </div>
    <div class="mb-4">
        <label for="id_socioeconomic_status" class="block text-gray-700 text-sm font-bold mb-2">Socioeconomic Status</label>
        {{ form.socioeconomic_status }}
    </div>
    <div class="flex items-center justify-between">
        <button id="save-button" type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            Save
        </button>
    </div>
</form>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        // Function to handle form submission
        $('#demographic-info-form').submit(function(event) {
            event.preventDefault(); // Prevent default form submission
            
            // Perform AJAX form submission
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(response) {
                    // Form submitted successfully
                    if (response.success) {
                        $('.card p:nth-child(2)').html(`<strong>Age:</strong> ${response.age}`);
                        $('.card p:nth-child(3)').html(`<strong>Gender:</strong> ${response.sex}`);
                        $('.card p:nth-child(4)').html(`<strong>Ethnicity/Race:</strong> ${response.ethnicity_race}`);
                        $('.card p:nth-child(5)').html(`<strong>Socioeconomic Status:</strong> ${response.socioeconomic_status}`);

                        closeForm();
                    } else {
                        alert(response.message);
                    }
                    // You can also handle response data here if needed
                },
                error: function(xhr, status, error) {
                    // Handle errors if needed
                    console.error('Error:', error);
                }
            });
        });

        // Function to close the form
        function closeForm() {
            $('#demographic-info-form').addClass('hidden');
        }
    });
</script>

apps/users/templates/users/edit_biometric_data_form.html
<form id="biometric-data-form" method="post" action="{% url 'users:edit_biometric_data' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="id_height" class="block text-gray-700 text-sm font-bold mb-2">Height:</label>
        {{ form.height }}
    </div>
    <div class="mb-4">
        <label for="id_weight" class="block text-gray-700 text-sm font-bold mb-2">Weight:</label>
        {{ form.weight }}
    </div>
    <div class="mb-4">
        <label for="id_blood_pressure" class="block text-gray-700 text-sm font-bold mb-2">Blood Pressure:</label>
        {{ form.blood_pressure }}
    </div>
    <div class="mb-4">
        <label for="id_cholesterol_levels" class="block text-gray-700 text-sm font-bold mb-2">Cholesterol Level:</label>
        {{ form.cholesterol_levels }}
    </div>
    <div class="mb-4">
        <label for="id_blood_glucose_levels" class="block text-gray-700 text-sm font-bold mb-2">Blood Glucose Levels:</label>
        {{ form.blood_glucose_levels }}
    </div>
    <div class="flex items-center justify-between">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Save</button>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('#biometric-data-form').submit(function(event) {
            event.preventDefault();

            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(response) {
                    if (response.success) {
                       $('#card-3 p:nth-child(2)').html(`Height: ${response.height}`);
                       $('#card-3 p:nth-child(3)').html(`Weight: ${response.weight}`);
                       $('#card-3 p:nth-child(4)').html(`Blood Pressure: ${response.blood_pressure}`);
                       $('#card-3 p:nth-child(5)').html(`Cholesterol Levels: ${response.cholesterol_levels}`);
                       $('#card-3 p:nth-child(6)').html(`Blood Glucose Levels: ${response.blood_glucose_levels}`);

                       closeForm();
                    } else {
                        alert(response.message);
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        });

        function closeForm() {
            $('#biometric-data-form').addClass('hidden');
        }
    });
</script>

apps/users/templates/users/edit_env_factors_form.html
{% load widget_tweaks %}

<form id="env-factors-form" action="{% url 'users:edit_env_factors' %}" method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="id_air_pollution_exposure" class="block text-gray-700 text-sm font-bold mb-2">Air Pollution Exposure:</label>
        <div class="relative">
            {{ form.air_pollution_exposure|addclass:"block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline" }}
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
            </div>
        </div>
    </div>
    <div class="mb-4">
        <label for="id_occupational_hazards" class="block text-gray-700 text-sm font-bold mb-2">Occupational Hazards:</label>
        <div class="relative">
            {{ form.occupational_hazards|addclass:"block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline" }}
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
            </div>
        </div>
    </div>
    <div class="mb-4">
        <label for="id_clean_drinking_water_access" class="block text-gray-700 text-sm font-bold mb-2">Access to clean drinking water:</label>
        <div class="relative">
            {{ form.clean_drinking_water_access|addclass:"block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline" }}
            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
            </div>
        </div>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('#env-factors-form').submit(function(event) {
            event.preventDefault();

            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(response) {
                    if (response.success) {
                        $('#card-4 p:nth-child(2)').html(`Air Pollution Exposure: ${response.air_pollution_exposure}`);
                        $('#card-4 p:nth-child(3)').html(`Occupation Hazzards: ${response.occupational_hazards}`);
                        $('#card-4 p:nth-child(4)').html(`Access to clean drinking water: ${response.clean_drinking_water_access}`);

                        closeForm();
                    } else {
                        alert(response.message);
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        });

        function closeForm() {
            $('#env-factors-form').addClass('hidden');
        }
    });
</script>

apps/users/templates/users/edit_lifestyle_info_form.html
<form id="lifestyle-info-form" action="{% url 'users:edit_lifestyle_info' %}" class="bg-white shadow-md rounded px-8 pt-6 pb-6 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="id_typical_daily_diet" class="block text-gray-700 text-sm font-bold mb-2">Daily Diet:</label>
        {{ form.typical_daily_diet }}
    </div>
    <div class="mb-4">
        <label for="id_physical_activity" class="block text-gray-700 text-sm font-bold mb-2">Physical Activity:</label>
        {{ form.physical_activity_frequency }}
    </div>
    <div class="mb-4">
        <label for="id_smoking_habits" class="block text-gray-700 text-sm font-bold mb-2">Tobaco Use:</label>
        {{ form.smoking_habits }}
    </div>
    <div class="mb-4">
        <label for="id_alcohol_consumption" class="block text-gray-700 text-sm font-bold mb-2">Alcohol Consumption:</label>
        {{ form.alcohol_consumption }}
    </div>
    <div class="mb-4">
        <label for="id_recreational_drug_use" class="block text-gray-700 text-sm font-bold mb-2">Recreational Drug Use:</label>
         {{ form.recreational_drug_use }}
    </div>
    <div class="mb-4">
        <label for="id_stress_management_methods" class="block text-gray-700 text-sm font-bold mb-2">Stress Management:</label>
        {{ form.stress_management_methods }}
    </div>

    <div class="flex items-center justify-between">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Save</button>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $(document).ready(function() {
        $('#lifestyle-info-form').submit(function(event) {
            event.preventDefault();
            $.ajax({ // Note the '.' before 'ajax'
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(response) {
                    if (response.success) {
                        $('#card-2 p:nth-child(2)').html(`Daily Diet: ${response.typical_daily_diet}`);
                        $('#card-2 p:nth-child(3)').html(`Physical Activity: ${response.physical_activity_frequency}`);
                        $('#card-2 p:nth-child(4)').html(`Tobacco Use: ${response.smoking_habits}`);
                        $('#card-2 p:nth-child(5)').html(`Alcohol Consumption: ${response.alcohol_consumption}`);
                        $('#card-2 p:nth-child(6)').html(`Recreational Drug Use: ${response.recreational_drug_use}`);
                        $('#card-2 p:nth-child(7)').html(`Stress Management: ${response.stress_management_methods}`);
                        closeForm();
                    } else {
                        alert(response.message);
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        });

        function closeForm() {
            $('#lifestyle-info-form').addClass('hidden');
        }
    });
</script>

apps/users/templates/users/edit_med_hist_form.html
<form id="medical-history-form" action="{% url 'users:edit_med_hist' %}" method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="id_family_history_chronic_diseases" class="block text-gray-700 text-sm font-bold mb-2">Family History of Chronic Diseases:</label>
        {{ form.family_history_chronic_diseases }}
        {% if form.family_history_chronic_diseases.errors %}
            <div class="text-red-500">{{ form.family_history_chronic_diseases.errors }}</div>
        {% endif %}
    </div>
    <div class="mb-4">
        <label for="id_diagnosed_chronic_conditions" class="block text-gray-700 text-sm font-bold mb-2">Diagnosed Chronic Conditions:</label>
        {{ form.diagnosed_chronic_conditions }}
        {% if form.diagnosed_chronic_conditions.errors %}
            <div class="text-red-500">{{ form.diagnosed_chronic_conditions.errors }}</div>
        {% endif %}
    </div>
    <div class="mb-4">
        <label for="id_medications" class="block text-gray-700 text-sm font-bold mb-2">Medications:</label>
        {{ form.medications }}
        {% if form.medications.errors %}
            <div class="text-red-500">{{ form.medications.errors }}</div>
        {% endif %}
    </div>
    <div class="mb-4">
        <label for="id_surgeries" class="block text-gray-700 text-sm font-bold mb-2">Surgeries:</label>
        {{ form.surgeries }}
        {% if form.surgeries.errors %}
            <div class="text-red-500">{{ form.surgeries.errors }}</div>
        {% endif %}
    </div>
    <div class="flex items-center justify-between">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Save</button>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('#medical-history-form').submit(function (event) {
            event.preventDefault();

            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(response) {
                    if (response.success) {
                        $('#card-1 p:nth-child(2)').html(`<strong>Family History of Chronic Diseases:</strong> ${response.family_history_chronic_diseases}`);
                        $('#card-1 p:nth-child(3)').html(`<strong>Diagnosed Chronic Conditions:</strong> ${response.diagnosed_chronic_conditions}`);
                        $('#card-1 p:nth-child(4)').html(`<strong>Medications:</strong> ${response.medications}`);
                        $('#card-1 p:nth-child(5)').html(`<strong>Surgeries:</strong> ${response.surgeries}`);

                        closeForm();
                    } else {
                        alert(response.message);
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        });

        function closeForm() {
            $('#medical-history-form').addClass('hidden');
        }
    });
</script>